#!/usr/bin/env zsh
#
#
#
#
#
echo "INSTALL!"
echo "ENTER to start "
read

#umount /mnt
#umount /dev/sdb2

#swapoff /dev/sdb1

#My pre added PAckages
alias pacman="pacman --noconfirm" 
# pacman -Sy --needed git 

# PACKAGE LISTS...

declare -a pk=( "linux-firmware" "fish" "dkms" "zsh" "linux-headers" "networkmanager" "git" "dkms" "base-devel" "w3m" "htop" "vim" "nano" "wget" "awesome" "deepin" "deepin-extra" "sddm" "python" "yay" "grub" "arch-install-scripts" "archiso" "tk" "libreoffice-fresh"  "cool-retro-term" "breeze" "blackmate" "blackman" "dkms" "apparmor" "blackman" "sherlock" "recon-ng" "maltego" "nmap" "hashcat" "dirbuster" "gobuster" "nikto" "partitionmanager" "vim" "nano" "xscreensaver" )
declare -a pka=( "brave-bin" "visual-studio-code-bin" "tor" "torbrowser-launcher")
for a in "$@"; do
	pka+=( "$a" )
done

#pk+=" $pk_base"
#pk+=" $pk_dsk"
#pk+=" $pk_dev"
#pk+=" $pk_tools"

#pk+=" $pk_hack"
read
inst() {
    #chmod +x *
    chmod +x ./f0rn3u5-install
    chmod +x ./rtl8192eu-install
    cp ./f0rn3u5-install /usr/sbin/f0rn3u5-install
    cp  ./f0rn3u5-install  /mnt/usr/sbin/f0rn3u5-install
    cp ./rtl8192eu-install /mnt/usr/sbin/f0rn3u5-install
)
alias bi="pacstrap /mnt linux base"
 
#PART
echo "Make a partition"
wipefs /dev/sdb
cfdisk /dev/sdb
rootfs="/dev/sdb1"
umount $rootfs
swapoff $swap
wipefs $rootfs
mkfs.ext4 /dev/sdb1 -F
mount /dev/sdb1 /mnt
bi
inst
echo 'KEYMAP=de-latin1' > /mnt/etc/vconsole.conf
#genfstab /mnt > /mnt/etc/fstab
cp -r $(pwd) /mnt/git/f0rn3u5-arch-installer
#OT
blackarch() {
	curl https://blackarch.org/strap.sh | arch-chroot /mnt bash
	cp ./blackarch-init.conf /mnt/etc/pacman.conf
	arch-chroot /mnt pacman -Syy
}
alias a="arch-chroot /mnt"
a pacman-key --init
a dirmngr < /dev/null
a pacman-key -r 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
da pacman-key --lsign-key 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
blackarch
 
#a grub-mkconfig -o /boot/grub/grub.cfg

pkg() {
	for p in $pk; do
		a pacman --noconfirm --needed -S "$p"
	done;
}
pkg
arch-chroot /mnt systemctl enable NetworkManager
arch-chroot /mnt systemctl enable wpa_supplicant
#arch-chroot /mnt pacman --needed --noconfirm -S $pkg_dsk
a systemctl enable sddm
# snap install --classic powershell
#a snap install --classic code
#arch-chroot /mnt pacman --needed --noconfirm -S $pk_tools
#arch-chroot /mnt pacman -S blackarch-keyring blackarch-mirrorlist archstrike-mirrotlist archstrike-keyring
#arch-chroot /mnt pacman --needed --noconfirm -S $pk_dev
a blackmate
mkdir /mnt/git
git clone https://github.com/Mange/rtl8192eu-linux-driver /mnt/git/rtl8192eu
chmod 777 /mnt/git --recursive
a dkms add /mnt/git/rtl8192eu
a dkms add /git/rtl8192eu
for a in {1...50}; do
	echo ""
done
echo "root-password?"
echo ""
a passwd root
a passwd -u root
echo ""
echo "#-#"
echo ""
echo 'sophie-linux' > /mnt/etc/hostname
vared -p "Enter USERNAME " -c nm
arch-chroot /mnt useradd "$nm"
mkdir "/mnt/home/$nm"
a chown "/home/$nm" --recursive
arch-chroot /mnt chown "$nm" "/mnt/home/$nm"--recursive
chmod 777 /mnt/tmp --recursive
chmod 777 /mnt/home --reuursive
chmod 777 /mnt/root --recursive
echo "$nm ALL=(ALL) NOPASSWD: ALL" >> "/mnt/etc/sudoers.d/999$nm"
for a in $pka; do
	a sudo -u "$nm" yay -S --noconfirm $a
done
arch-chroot /mnt passwd "$nm"
arch-chroot /mnt chsh -s /usr/bin/fish "$nm"
a chsh -s /usr/bin/fish root
a chown "$nm" /home --recursive
arch-chroot /mnt sudo -u "$nm" yay -S --noconfirm brave-bin
for a in {1...50}
	echo ""
done
a grub-install /dev/sdb
a grub-mkconfig -o /boot/grub/grub.cfg
echo "To Install packages, tippe yay -Sy gefolgt vom paketnamen"
echo "Aktualisiert witd mit yay -Syu"
echo "ENTER to reboot!"

read

reboot
